# Generated by Django 3.2.3 on 2021-05-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Please make sure this is a working email', max_length=255, unique=True)),
                ('phone', models.CharField(help_text='We will be reaching on this line', max_length=20)),
                ('date_of_birth', models.CharField(blank=True, help_text='Format = YY-MM-DD', max_length=20)),
                ('current_qualification', models.CharField(blank=True, max_length=200)),
                ('select_course', models.CharField(choices=[('DIPLOMA IN ACCOUNTING', 'DIPLOMA IN ACCOUNTING'), ('DIPLOMA IN BUSINESS ADMINISTRATION', 'DIPLOMA IN BUSINESS ADMINISTRATION'), ('DIPLOMA IN OFFICE MANAGEMENT ', 'DIPLOMA IN OFFICE MANAGEMENT '), ('DIPLOMA IN INFORMATION TECHNOLOGY ', 'DIPLOMA IN INFORMATION TECHNOLOGY '), ('CERTIFICATE IN ACCOUNTING ', 'CERTIFICATE IN ACCOUNTING'), ('CERTIFICATE IN BUSINESS STUDIES ', 'CERTIFICATE IN BUSINESS STUDIES'), ('CERTIFICATE IN SECRETARIAL DUTIES ', 'CERTIFICATE IN SECRETARIAL DUTIES '), ('WEB DEVELOPMENT', 'WEB DEVELOPMENT'), ('MOBILE APP DEVELOPMENT', 'MOBILE APP DEVELOPMENT'), ('NETWORKING', 'NETWORKING')], max_length=100)),
                ('profile_picture', models.ImageField(blank=True, upload_to='student_pics')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
