# Generated by Django 3.2.3 on 2021-06-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chriswellschool', '0003_registerstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
    ]
