# Generated by Django 3.2.3 on 2021-06-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chriswellschool', '0004_registerstudent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerstudent',
            name='select_course',
            field=models.CharField(max_length=100),
        ),
    ]
