# Generated by Django 3.2.3 on 2021-06-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chriswellschool', '0005_alter_registerstudent_select_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerstudent',
            old_name='select_course',
            new_name='course',
        ),
    ]
